### ISSUE TITLE
Issue with [[include:filename]]

### ISSUE THREAD

**Issue by unsafecode** [christopherthielen/typedoc-plugin-external-module-name#7] opened 2017-02-24 08:46 UTC
## Issue
Looks like that if you use this plugin, `[[include:filename]]` syntax with `@module Name` doesn't output the content in the docs.

## Reproduction
In detail:
```
/**
 * @module Sample
 * 
 * [[include:sample.md]]
 */
/** DO NOT REMOVE */
```

**Does not** actually include `sample.md`.

On the other hand, this works, without having the plugin installed:

```
/**
 * [[include:sample.md]]
 */
```
But you then lack the module feature, which is key in large applications.

The only workaround is:
```
/**
 * @module Sample
 * 
 */
/** DO NOT REMOVE */

/**
 * [[include:sample.md]]
 */
export const description = "";
```
In which the initial "paragraph" is still blank, but at least you can finally include an external file by attaching it to a fake exported member.

##Asks
Support the `[[include:filename]]` syntax with `@module Name`

## Versions
`typescript@2.1.6 or @2.2.1`
`typedoc@0.5.7`
`typedoc-plugin-external-module-name@1.0.8`

**Comment by christopherthielen** [comment] 2017-10-27 19:13
I suspect this is a duplicate of #5 

Can you try:

1) Move the `@module` tag to below the include block

2) Keep the `@module` tag where it is but install `typedoc-plugin-single-line-tags`

**Comment by christopherthielen** [comment] 2017-10-27 19:34
I suspect this is fixed by `typedoc-plugin-single-line-tags` so closing for now

**Closed by christopherthielen** 2017-10-27 19:34 UTC
